# Generated by Django 5.1.1 on 2025-04-15 16:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('password_member', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TableBuuking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_total_people', models.PositiveIntegerField()),
                ('location', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Buuking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('member', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='buuking_core.member')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='buuking_core.product')),
                ('table', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='buuking_core.tablebuuking')),
            ],
        ),
    ]
